### ISSUE TITLE
new readme and code along

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/oo-custom-errors#1]
@jmburges 
will come right before triangle lab in deeper dive into OO unit

**Comment by jmburges** [comment]
Just some backtick errors. 

Also maybe adding the fact that if you rescue on a parent exception it will also grab all of it's sub-exceptions. 

Oh and I would add that you can get more information on exceptions like this

``` ruby
begin
  raise ZeroDivisionError, "Hello I am a random zero division error"
rescue ZeroDivisionError => e
  puts e.message
end
```

**Comment by jmburges** [comment]
also is this really required? I know it's required for the triangle lab but except for that lab do we ever do custom errors in like _any_ of the labs? Maybe it can go in some sort of advanced ruby unit down the road with the meta-programming stuff?
