### ISSUE TITLE
Link in article is dead

### ISSUE THREAD

**Issue by scarsam** [learn-co-curriculum/oo-custom-errors#17]
This is a code along. There are no tests to pass, but you must manually fork and clone the repo in order to code along!

I get 404 when clicking this link:
https://learn.co/tracks/full-stack-web-dev-with-react/object-oriented-ruby/metaprogramming/help.learn.co/workflow-tips/github/how-to-manually-open-a-lab

**Comment by gj** [comment]
Fixed in f309b04. Thanks @scarsam !
