### ISSUE TITLE
Reference to Prior Knowledge

### ISSUE THREAD

**Issue by orenmagid** [learn-co-curriculum/oo-custom-errors#18]
"We already know that Ruby has a hierarchy of error, or Exception, classes, all of which inherit from the Exception class." This is not a big deal, but I don't think this has been covered prior to this code-along.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
