### ISSUE TITLE
Spec Folder Missing

### ISSUE THREAD

**Issue by ShaylaWhite** [learn-co-curriculum/oo-custom-errors#21]

**Comment by maxwellbenton** [comment]
Hi @ShaylaWhite,

I am looking into this issue now, but was hoping you might be able to provide some additional information. This lesson is not a lab, does not have tests, and should be behaving like a code-along. Were you prompted to submit passing tests in Learn to register completion of this lesson?

**Comment by ShaylaWhite** [comment]
Sorry I think it was a misunderstanding on my part.

**Comment by maxwellbenton** [comment]
Okay, thank you for letting us know! I am going to go ahead and close this issue then.
